# Generated by Django 2.2.24 on 2026-02-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='STUDENT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
