# Generated by Django 2.2.24 on 2026-02-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20260204_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='post',
        ),
    ]
