# Generated by Django 2.2.24 on 2026-03-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20260221_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertsub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=200)),
                ('ALERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Alert')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
