# Generated by Django 2.0.9 on 2026-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alertsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
