# Generated by Django 2.2.24 on 2026-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
